### ISSUE TITLE
PhotoM tiptilt mirror code

### ISSUE THREAD

**Issue by YangLiujames** [czbiohub/coPylot#140]
This code is only for the slow scan mirror. The COM port needs to be change in the code to the device that is being used

**Comment by jamesliu1990** [comment]
The tiptilt mirror can not exceed value of 1 for both axis.. X^2+Y^2<1

**Comment by edyoshikun** [comment]
@AhmetCanSolak @YangLiujames are these things implemented yet? Also, I was wondering if for photom we need to use a DAC?

**Comment by edyoshikun** [comment]
I think for the initial test, we can probably do the USB. I did notice from the old photom-repo that the dac is mainly used to do the different scanning patterns. For ablation, I don't think we need this but for photoconversion, this might be a a good thing to work on next. We can close this issue and feel free to add a new issue regarding dac control. Thank you both

**Comment by AhmetCanSolak** [comment]
then I am closing this issue, anyone can create a new issue on dac control when they needed.
