### ISSUE TITLE
Adding Black styling

### ISSUE THREAD

**Issue by AhmetCanSolak** [czbiohub/coPylot#50]
We need to add https://github.com/psf/black to our project to keep styling consistent. Also it is very useful to have black as a pre-commit hook to make sure no contributor skipping black while committing.

Recommended `pyproject.toml` given below: 

```
[tool.black]
target-version = ['py36', 'py37']
skip-string-normalization = true
```

**Comment by AhmetCanSolak** [comment]
#56 works well, I tested, closing this issue, thank you @ljjh20

**Comment by edyoshikun** [comment]
@AhmetCanSolak  is there a reason why we want to have those target versions? 
I'm having issues fixing my black formatting on #148 given the current `.toml` configuration. 

```
[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
```

**Comment by AhmetCanSolak** [comment]
Target versions are there for legacy reasons. Addressing here: #150, please review then we  can merge quickly

**Comment by AhmetCanSolak** [comment]
#150 is merged, let me know if I can do anything else @edyoshikun , if nothing feel free to close this issue.
